### ISSUE TITLE
Create networkpolicies for the Syn ArgoCD instance

### ISSUE THREAD

**Issue by simu** [projectsyn/component-argocd#149]
## Context

Currently, we don't create any networkpolicies to isolate the Project Syn ArgoCD from the rest of the cluster. We should make sure that we deploy network policies in the `syn` namespace which isolate the ArgoCD instance from other workloads on the cluster.

## Task deliverables

* The component deploys network policies that isolate the `syn` namespace from other workloads on the cluster
* The network policies are configured so that the argocd-operator and the cluster's monitoring stack can still access workloads in the `syn` namespace
* The networkpolicies use names that are unlikely to conflict with other networkpolicies that are deployed cluster-wide (e.g. on APPUiO Managed OCP4)

**Comment by HappyTetrahedron** [comment]
Implemented in v8.5.0
